// Platform configurations with colors and LibRetro system names
export const platformConfig = {
  SNES: {
    color: "#8B5CF6",
    gradient: "from-purple-600 to-indigo-700",
    icon: "🎮",
    logo: "/logos/snes.svg",
    libretro: "Nintendo - Super Nintendo Entertainment System",
    arkosFolder: "snes",
    retrostic: "snes",
    romspedia: "super-nintendo",
  },
  GBA: {
    color: "#3B82F6",
    gradient: "from-blue-500 to-indigo-600",
    icon: "📱",
    logo: "/logos/gba.svg",
    libretro: "Nintendo - Game Boy Advance",
    arkosFolder: "gba",
    retrostic: "gba",
    romspedia: "gameboy-advance",
  },
  Genesis: {
    color: "#EF4444",
    gradient: "from-red-500 to-rose-600",
    icon: "🎯",
    logo: "/logos/genesis.svg",
    libretro: "Sega - Mega Drive - Genesis",
    arkosFolder: "genesis",
    retrostic: "genesis",
    romspedia: "sega-genesis",
  },
  NES: {
    color: "#F59E0B",
    gradient: "from-amber-500 to-orange-600",
    icon: "🕹️",
    logo: "/logos/nes.svg",
    libretro: "Nintendo - Nintendo Entertainment System",
    arkosFolder: "nes",
    retrostic: "nes",
    romspedia: "nintendo",
  },
  N64: {
    color: "#10B981",
    gradient: "from-emerald-500 to-teal-600",
    icon: "🎲",
    logo: "/logos/n64.svg",
    libretro: "Nintendo - Nintendo 64",
    arkosFolder: "n64",
    retrostic: "n64",
    romspedia: "nintendo-64",
  },
  PS1: {
    color: "#6366F1",
    gradient: "from-indigo-500 to-purple-600",
    icon: "💿",
    logo: "/logos/ps1.svg",
    libretro: "Sony - PlayStation",
    arkosFolder: "psx",
    retrostic: "ps-1",
    romspedia: "playstation-1",
  },
  "GB/GBC": {
    color: "#84CC16",
    gradient: "from-lime-500 to-green-600",
    icon: "🔋",
    logo: "/logos/gb-gbc.svg",
    libretro: "Nintendo - Game Boy Color",
    arkosFolder: "gbc",
    retrostic: "gbc",
    romspedia: "gameboy-color",
  },
  Saturn: {
    color: "#EC4899",
    gradient: "from-pink-500 to-fuchsia-600",
    icon: "🪐",
    logo: "/logos/saturn.svg",
    libretro: "Sega - Saturn",
    arkosFolder: "saturn",
    retrostic: "saturn",
    romspedia: "sega-saturn",
  },
  "Master System": {
    color: "#E11D48",
    gradient: "from-red-500 to-rose-600",
    icon: "🎮",
    logo: "/logos/sms.svg",
    libretro: "Sega - Master System - Mark III",
    arkosFolder: "mastersystem",
    retrostic: "master-system",
    romspedia: "sega-master-system",
  },
  All: {
    color: "#1F2937", // gray-800
    gradient: "from-gray-700 to-gray-900",
    icon: "♾️",
    logo: "/logo.png", // Assuming a generic logo exists
    libretro: null,
    arkosFolder: null,
    retrostic: null,
    romspedia: null,
  },
};

export const allGames = [
  // SNES (39 games)
  {
    id: "snes-1",
    name: "Chrono Trigger",
    platform: "SNES",
    genres: ["RPG"],
    notes: "Perfect pacing, multiple endings",
    gem: false,
    libretroName: "Chrono Trigger (USA)",
  },
  {
    id: "snes-2",
    name: "Final Fantasy VI",
    platform: "SNES",
    genres: ["RPG"],
    notes: "Epic 40+ hour adventure, best villain",
    gem: false,
    libretroName: "Final Fantasy III (USA)",
  },
  {
    id: "snes-3",
    name: "Super Metroid",
    platform: "SNES",
    genres: ["Action", "Adventure"],
    notes: "Gold standard Metroidvania",
    gem: false,
    libretroName: "Super Metroid (Japan, USA) (En,Ja)",
  },
  {
    id: "snes-4",
    name: "The Legend of Zelda: A Link to the Past",
    platform: "SNES",
    genres: ["Action", "Adventure"],
    notes: "Masterful dungeon design",
    gem: false,
    libretroName: "Legend of Zelda, The - A Link to the Past (USA)",
  },
  {
    id: "snes-5",
    name: "Super Mario World",
    platform: "SNES",
    genres: ["Platformer"],
    notes: "Definitive 2D Mario",
    gem: false,
    libretroName: "Super Mario World (USA)",
  },
  {
    id: "snes-6",
    name: "EarthBound",
    platform: "SNES",
    genres: ["RPG"],
    notes: "Quirky humor, influential",
    gem: false,
    libretroName: "EarthBound (USA)",
  },
  {
    id: "snes-7",
    name: "Super Mario RPG",
    platform: "SNES",
    genres: ["RPG"],
    notes: "Spawned Paper Mario series",
    gem: false,
    libretroName: "Super Mario RPG - Legend of the Seven Stars (USA)",
  },
  {
    id: "snes-8",
    name: "Donkey Kong Country 2",
    platform: "SNES",
    genres: ["Platformer"],
    notes: "Tighter than original, amazing OST",
    gem: false,
    libretroName: "Donkey Kong Country 2 - Diddy's Kong Quest (USA) (En,Fr)",
  },
  {
    id: "snes-9",
    name: "Secret of Mana",
    platform: "SNES",
    genres: ["Action", "RPG"],
    notes: "Beautiful multiplayer action-RPG",
    gem: false,
    libretroName: "Secret of Mana (USA)",
  },
  {
    id: "snes-10",
    name: "Mega Man X",
    platform: "SNES",
    genres: ["Platformer", "Action"],
    notes: "Perfect evolution of series",
    gem: false,
    libretroName: "Mega Man X (USA)",
  },
  {
    id: "snes-11",
    name: "Super Castlevania IV",
    platform: "SNES",
    genres: ["Action"],
    notes: "8-directional whip, atmospheric",
    gem: false,
    libretroName: "Super Castlevania IV (USA)",
  },
  {
    id: "snes-12",
    name: "Yoshi's Island",
    platform: "SNES",
    genres: ["Platformer"],
    notes: "Hand-drawn visuals, inventive",
    gem: false,
    libretroName: "Super Mario World 2 - Yoshi's Island (USA)",
  },
  {
    id: "snes-13",
    name: "Kirby Super Star",
    platform: "SNES",
    genres: ["Platformer"],
    notes: "Eight games in one",
    gem: false,
    libretroName: "Kirby Super Star (USA)",
  },
  {
    id: "snes-14",
    name: "Contra III: The Alien Wars",
    platform: "SNES",
    genres: ["Action"],
    notes: "Intense 2-player action",
    gem: false,
    libretroName: "Contra III - The Alien Wars (USA)",
  },
  {
    id: "snes-15",
    name: "Street Fighter II Turbo",
    platform: "SNES",
    genres: ["Fighting"],
    notes: "Definitive 16-bit fighter",
    gem: false,
    libretroName: "Street Fighter II Turbo (USA)",
  },
  {
    id: "snes-16",
    name: "TMNT IV: Turtles in Time",
    platform: "SNES",
    genres: ["Beat-Em-Up"],
    notes: "Pinnacle of the genre",
    gem: false,
    libretroName: "Teenage Mutant Ninja Turtles IV - Turtles in Time (USA)",
  },
  {
    id: "snes-17",
    name: "Lufia II: Rise of the Sinistrals",
    platform: "SNES",
    genres: ["RPG", "Puzzle"],
    notes: "Great puzzles",
    gem: true,
    libretroName: "Lufia II - Rise of the Sinistrals (USA)",
  },
  {
    id: "snes-18",
    name: "Terranigma",
    platform: "SNES",
    genres: ["Action", "RPG"],
    notes: "Quintet masterpiece",
    gem: true,
    libretroName: "Terranigma (Europe)",
  },
  {
    id: "snes-19",
    name: "ActRaiser",
    platform: "SNES",
    genres: ["Action", "Simulation"],
    notes: "Unique hybrid",
    gem: true,
    libretroName: "ActRaiser (USA)",
  },
  {
    id: "snes-20",
    name: "Final Fantasy IV",
    platform: "SNES",
    genres: ["RPG"],
    notes: "Pioneered ATB system",
    gem: false,
    libretroName: "Final Fantasy II (USA)",
  },
  {
    id: "snes-21",
    name: "Donkey Kong Country",
    platform: "SNES",
    genres: ["Platformer"],
    notes: "Revolutionary graphics",
    gem: false,
    libretroName: "Donkey Kong Country (USA) (Rev 2)",
  },
  {
    id: "snes-22",
    name: "The Legend of the Mystical Ninja",
    platform: "SNES",
    genres: ["Action"],
    notes: "Whimsical co-op",
    gem: true,
    libretroName: "Legend of the Mystical Ninja, The (USA)",
  },
  {
    id: "snes-23",
    name: "Zombies Ate My Neighbors",
    platform: "SNES",
    genres: ["Action"],
    notes: "B-movie charm",
    gem: true,
    libretroName: "Zombies Ate My Neighbors (USA)",
  },
  {
    id: "snes-24",
    name: "F-Zero",
    platform: "SNES",
    genres: ["Racing"],
    notes: "Blazing fast Mode 7 racer",
    gem: false,
    libretroName: "F-Zero (USA)",
  },
  {
    id: "snes-25",
    name: "Super Mario Kart",
    platform: "SNES",
    genres: ["Racing"],
    notes: "Template for all kart racers",
    gem: false,
    libretroName: "Super Mario Kart (USA)",
  },
  {
    id: "snes-26",
    name: "NBA Jam: Tournament Edition",
    platform: "SNES",
    genres: ["Sports"],
    notes: "Arcade basketball perfection",
    gem: false,
    libretroName: "NBA Jam - Tournament Edition (USA)",
  },
  {
    id: "snes-27",
    name: "Super Punch-Out!!",
    platform: "SNES",
    genres: ["Sports"],
    notes: "Pattern-based boxing",
    gem: false,
    libretroName: "Super Punch-Out!! (USA)",
  },
  {
    id: "snes-28",
    name: "Tetris Attack",
    platform: "SNES",
    genres: ["Puzzle"],
    notes: "Addictive block-matching",
    gem: true,
    libretroName: "Tetris Attack (USA) (En,Ja)",
  },
  {
    id: "snes-29",
    name: "The Lost Vikings",
    platform: "SNES",
    genres: ["Puzzle", "Platformer"],
    notes: "Blizzard classic",
    gem: true,
    libretroName: "Lost Vikings, The (USA)",
  },
  {
    id: "snes-30",
    name: "SimCity",
    platform: "SNES",
    genres: ["Simulation"],
    notes: "Excellent Nintendo port",
    gem: false,
    libretroName: "SimCity (USA)",
  },
  {
    id: "snes-31",
    name: "Uniracers",
    platform: "SNES",
    genres: ["Racing"],
    notes: "Unicycle stunts, legally dead",
    gem: true,
    libretroName: "Uniracers (USA)",
  },
  {
    id: "snes-32",
    name: "EVO: Search for Eden",
    platform: "SNES",
    genres: ["Action", "RPG"],
    notes: "Evolve from fish to mammal",
    gem: true,
    libretroName: "E.V.O. - Search for Eden (USA)",
  },
  {
    id: "snes-33",
    name: "Kirby's Dream Course",
    platform: "SNES",
    genres: ["Puzzle", "Sports"],
    notes: "Kirby as golf ball",
    gem: true,
    libretroName: "Kirby's Dream Course (USA)",
  },
  {
    id: "snes-34",
    name: "On the Ball",
    platform: "SNES",
    genres: ["Puzzle"],
    notes: "Rotate the maze",
    gem: true,
    libretroName: "On the Ball (USA)",
  },
  {
    id: "snes-35",
    name: "Lemmings",
    platform: "SNES",
    genres: ["Puzzle"],
    notes: "Save suicidal creatures",
    gem: false,
    libretroName: "Lemmings (USA)",
  },
  {
    id: "snes-36",
    name: "Out of This World",
    platform: "SNES",
    genres: ["Platformer", "Adventure"],
    notes: "Rotoscoped alien survival",
    gem: false,
    libretroName: "Out of This World (USA)",
  },
  {
    id: "snes-37",
    name: "Space Megaforce",
    platform: "SNES",
    genres: ["Shmup"],
    notes: "Compile's best shooter",
    gem: true,
    libretroName: "Super Aleste (Japan)",
  },
  {
    id: "snes-38",
    name: "Disney's Aladdin",
    platform: "SNES",
    genres: ["Platformer", "Action"],
    notes: "Capcom's tight platformer, Shinji Mikami directed",
    gem: false,
    libretroName: "Disney's Aladdin (USA)",
  },
  {
    id: "snes-39",
    name: "Magical Pop'n",
    platform: "SNES",
    genres: ["Action", "Platformer"],
    notes: "Top-tier hidden gem, Metroidvania excellence",
    gem: true,
    libretroName: "Magical Pop'n (Japan)",
  },

  // GBA (38 games)
  {
    id: "gba-1",
    name: "Metroid Fusion",
    platform: "GBA",
    genres: ["Action", "Adventure"],
    notes: "Atmospheric with SA-X tension",
    gem: false,
    libretroName: "Metroid Fusion (USA)",
  },
  {
    id: "gba-2",
    name: "The Legend of Zelda: The Minish Cap",
    platform: "GBA",
    genres: ["Action", "Adventure"],
    notes: "Charming Capcom Zelda",
    gem: false,
    libretroName: "Legend of Zelda, The - The Minish Cap (USA)",
  },
  {
    id: "gba-3",
    name: "Pokémon Emerald",
    platform: "GBA",
    genres: ["RPG"],
    notes: "Definitive Gen III, Battle Frontier",
    gem: false,
    libretroName: "Pokemon - Emerald Version (USA, Europe)",
  },
  {
    id: "gba-4",
    name: "Fire Emblem",
    platform: "GBA",
    genres: ["Strategy", "RPG"],
    notes: "Western franchise debut",
    gem: false,
    libretroName: "Fire Emblem (USA, Australia)",
  },
  {
    id: "gba-5",
    name: "Castlevania: Aria of Sorrow",
    platform: "GBA",
    genres: ["Action", "Adventure"],
    notes: "Best GBA Castlevania",
    gem: false,
    libretroName: "Castlevania - Aria of Sorrow (USA)",
  },
  {
    id: "gba-6",
    name: "Advance Wars",
    platform: "GBA",
    genres: ["Strategy"],
    notes: "Accessible yet deep tactics",
    gem: false,
    libretroName: "Advance Wars (USA)",
  },
  {
    id: "gba-7",
    name: "Golden Sun",
    platform: "GBA",
    genres: ["RPG"],
    notes: "Finest original GBA RPG",
    gem: false,
    libretroName: "Golden Sun (USA, Europe)",
  },
  {
    id: "gba-8",
    name: "Final Fantasy Tactics Advance",
    platform: "GBA",
    genres: ["Strategy", "RPG"],
    notes: "Deep tactics with Laws",
    gem: false,
    libretroName: "Final Fantasy Tactics Advance (USA)",
  },
  {
    id: "gba-9",
    name: "Metroid: Zero Mission",
    platform: "GBA",
    genres: ["Action", "Adventure"],
    notes: "Brilliant remake",
    gem: false,
    libretroName: "Metroid - Zero Mission (USA)",
  },
  {
    id: "gba-10",
    name: "Mario & Luigi: Superstar Saga",
    platform: "GBA",
    genres: ["RPG"],
    notes: "Hilarious action-RPG",
    gem: false,
    libretroName: "Mario & Luigi - Superstar Saga (USA)",
  },
  {
    id: "gba-11",
    name: "Advance Wars 2: Black Hole Rising",
    platform: "GBA",
    genres: ["Strategy"],
    notes: "Refined sequel",
    gem: false,
    libretroName: "Advance Wars 2 - Black Hole Rising (USA)",
  },
  {
    id: "gba-12",
    name: "Fire Emblem: The Sacred Stones",
    platform: "GBA",
    genres: ["Strategy", "RPG"],
    notes: "More accessible entry",
    gem: false,
    libretroName: "Fire Emblem - The Sacred Stones (USA, Australia)",
  },
  {
    id: "gba-13",
    name: "Wario Land 4",
    platform: "GBA",
    genres: ["Platformer", "Puzzle"],
    notes: "Inventive puzzle-platformer",
    gem: false,
    libretroName: "Wario Land 4 (USA, Europe)",
  },
  {
    id: "gba-14",
    name: "Golden Sun: The Lost Age",
    platform: "GBA",
    genres: ["RPG"],
    notes: "Essential companion",
    gem: false,
    libretroName: "Golden Sun - The Lost Age (USA, Europe)",
  },
  {
    id: "gba-15",
    name: "Kirby & The Amazing Mirror",
    platform: "GBA",
    genres: ["Platformer", "Adventure"],
    notes: "Metroidvania Kirby",
    gem: true,
    libretroName: "Kirby & The Amazing Mirror (USA)",
  },
  {
    id: "gba-16",
    name: "Mario Kart: Super Circuit",
    platform: "GBA",
    genres: ["Racing"],
    notes: "40 tracks including SNES",
    gem: false,
    libretroName: "Mario Kart - Super Circuit (USA)",
  },
  {
    id: "gba-17",
    name: "Mega Man Zero 3",
    platform: "GBA",
    genres: ["Action", "Platformer"],
    notes: "Challenging, revitalized",
    gem: false,
    libretroName: "Mega Man Zero 3 (USA)",
  },
  {
    id: "gba-18",
    name: "Mother 3",
    platform: "GBA",
    genres: ["RPG"],
    notes: "Emotionally powerful",
    gem: true,
    libretroName: "Mother 3 (Japan)",
  },
  {
    id: "gba-19",
    name: "Astro Boy: Omega Factor",
    platform: "GBA",
    genres: ["Action"],
    notes: "Treasure masterpiece",
    gem: true,
    libretroName: "Astro Boy - Omega Factor (USA)",
  },
  {
    id: "gba-20",
    name: "Drill Dozer",
    platform: "GBA",
    genres: ["Action", "Platformer"],
    notes: "Game Freak gem",
    gem: true,
    libretroName: "Drill Dozer (USA)",
  },
  {
    id: "gba-21",
    name: "WarioWare, Inc.",
    platform: "GBA",
    genres: ["Party"],
    notes: "Revolutionary, replayable",
    gem: false,
    libretroName: "WarioWare, Inc. - Mega Microgame$! (USA)",
  },
  {
    id: "gba-22",
    name: "Final Fantasy VI Advance",
    platform: "GBA",
    genres: ["RPG"],
    notes: "Definitive portable version",
    gem: false,
    libretroName: "Final Fantasy VI Advance (USA)",
  },
  {
    id: "gba-23",
    name: "Tactics Ogre: Knight of Lodis",
    platform: "GBA",
    genres: ["Strategy", "RPG"],
    notes: "Morally complex",
    gem: true,
    libretroName: "Tactics Ogre - The Knight of Lodis (USA)",
  },
  {
    id: "gba-24",
    name: "Ninja Five-O",
    platform: "GBA",
    genres: ["Action"],
    notes: "Criminally overlooked",
    gem: true,
    libretroName: "Ninja Five-0 (USA)",
  },
  {
    id: "gba-25",
    name: "Gunstar Super Heroes",
    platform: "GBA",
    genres: ["Action"],
    notes: "Treasure's frantic sequel",
    gem: true,
    libretroName: "Gunstar Super Heroes (USA)",
  },
  {
    id: "gba-26",
    name: "Sonic Advance",
    platform: "GBA",
    genres: ["Platformer"],
    notes: "Best 2D Sonic on GBA",
    gem: false,
    libretroName: "Sonic Advance (USA)",
  },
  {
    id: "gba-27",
    name: "F-Zero: Maximum Velocity",
    platform: "GBA",
    genres: ["Racing"],
    notes: "Blazing fast Mode 7",
    gem: false,
    libretroName: "F-Zero - Maximum Velocity (USA)",
  },
  {
    id: "gba-28",
    name: "Mario Golf: Advance Tour",
    platform: "GBA",
    genres: ["Sports", "RPG"],
    notes: "Full RPG mode",
    gem: false,
    libretroName: "Mario Golf - Advance Tour (USA)",
  },
  {
    id: "gba-29",
    name: "Mario Tennis: Power Tour",
    platform: "GBA",
    genres: ["Sports", "RPG"],
    notes: "Deep career mode",
    gem: false,
    libretroName: "Mario Tennis - Power Tour (USA)",
  },
  {
    id: "gba-30",
    name: "Rhythm Tengoku",
    platform: "GBA",
    genres: ["Rhythm"],
    notes: "Japan-only predecessor",
    gem: true,
    libretroName: "Rhythm Tengoku (Japan)",
  },
  {
    id: "gba-31",
    name: "Pokémon Pinball: Ruby & Sapphire",
    platform: "GBA",
    genres: ["Pinball"],
    notes: "Catch 'em via flippers",
    gem: false,
    libretroName: "Pokemon Pinball - Ruby & Sapphire (USA)",
  },
  {
    id: "gba-32",
    name: "Kuru Kuru Kururin",
    platform: "GBA",
    genres: ["Puzzle"],
    notes: "Spinning stick mazes",
    gem: true,
    libretroName: "Kuru Kuru Kururin (Europe) (En,Fr,De,Es,It)",
  },
  {
    id: "gba-33",
    name: "ChuChu Rocket!",
    platform: "GBA",
    genres: ["Puzzle"],
    notes: "Frantic mouse-routing",
    gem: false,
    libretroName: "ChuChu Rocket! (USA)",
  },
  {
    id: "gba-34",
    name: "Pinball of the Dead",
    platform: "GBA",
    genres: ["Pinball"],
    notes: "Absurd and fun",
    gem: true,
    libretroName: "Pinball of the Dead, The (USA)",
  },
  {
    id: "gba-36",
    name: "DK: King of Swing",
    platform: "GBA",
    genres: ["Action"],
    notes: "L/R peg-climbing",
    gem: true,
    libretroName: "DK - King of Swing (USA)",
  },
  {
    id: "gba-37",
    name: "Denki Blocks",
    platform: "GBA",
    genres: ["Puzzle"],
    notes: "150+ brain-teasers",
    gem: true,
    libretroName: "Denki Blocks! (USA)",
  },
  {
    id: "gba-38",
    name: "Metal Slug Advance",
    platform: "GBA",
    genres: ["Action", "Platformer"],
    notes:
      "GBA-exclusive run-and-gun with card system, solid port of arcade chaos",
    gem: false,
    libretroName: "Metal Slug Advance (USA)",
  },
  {
    id: "gba-39",
    name: "Disney's Lilo & Stitch",
    platform: "GBA",
    genres: ["Action", "Platformer"],
    notes: "Metal Slug-style action, highly rated Disney sleeper",
    gem: true,
    libretroName: "Disney's Lilo & Stitch (USA)",
  },

  // Genesis (32 games)
  {
    id: "gen-1",
    name: "Sonic the Hedgehog 2",
    platform: "Genesis",
    genres: ["Platformer"],
    notes: "Definitive 16-bit Sonic",
    gem: false,
    libretroName: "Sonic The Hedgehog 2 (World)",
  },
  {
    id: "gen-2",
    name: "Streets of Rage 2",
    platform: "Genesis",
    genres: ["Beat-Em-Up"],
    notes: "Gold standard, iconic OST",
    gem: false,
    libretroName: "Streets of Rage 2 (USA)",
  },
  {
    id: "gen-3",
    name: "Gunstar Heroes",
    platform: "Genesis",
    genres: ["Action"],
    notes: "Treasure masterpiece",
    gem: false,
    libretroName: "Gunstar Heroes (USA)",
  },
  {
    id: "gen-4",
    name: "Phantasy Star IV",
    platform: "Genesis",
    genres: ["RPG"],
    notes: "One of best 16-bit JRPGs",
    gem: false,
    libretroName: "Phantasy Star IV (USA)",
  },
  {
    id: "gen-5",
    name: "Shining Force II",
    platform: "Genesis",
    genres: ["Strategy", "RPG"],
    notes: "Excellent tactical RPG",
    gem: false,
    libretroName: "Shining Force II (USA)",
  },
  {
    id: "gen-6",
    name: "Sonic 3 & Knuckles",
    platform: "Genesis",
    genres: ["Platformer"],
    notes: "Combined epic adventure",
    gem: false,
    libretroName: "Sonic 3 & Knuckles (USA)",
  },
  {
    id: "gen-7",
    name: "Castlevania: Bloodlines",
    platform: "Genesis",
    genres: ["Action"],
    notes: "Genesis exclusive",
    gem: false,
    libretroName: "Castlevania - Bloodlines (USA)",
  },
  {
    id: "gen-8",
    name: "Shinobi III",
    platform: "Genesis",
    genres: ["Action"],
    notes: "Peak ninja action",
    gem: false,
    libretroName: "Shinobi III - Return of the Ninja Master (USA)",
  },
  {
    id: "gen-9",
    name: "Thunder Force IV",
    platform: "Genesis",
    genres: ["Shmup"],
    notes: "Best Genesis shooter",
    gem: false,
    libretroName: "Thunder Force IV (Japan)",
  },
  {
    id: "gen-10",
    name: "Contra: Hard Corps",
    platform: "Genesis",
    genres: ["Action"],
    notes: "Arguably best Contra",
    gem: false,
    libretroName: "Contra - Hard Corps (USA)",
  },
  {
    id: "gen-11",
    name: "Dynamite Headdy",
    platform: "Genesis",
    genres: ["Platformer"],
    notes: "Head-swapping platformer",
    gem: false,
    libretroName: "Dynamite Headdy (USA)",
  },
  {
    id: "gen-12",
    name: "Castle of Illusion",
    platform: "Genesis",
    genres: ["Platformer"],
    notes: "Gorgeous Disney",
    gem: false,
    libretroName: "Castle of Illusion Starring Mickey Mouse (USA)",
  },
  {
    id: "gen-13",
    name: "Vectorman",
    platform: "Genesis",
    genres: ["Action"],
    notes: "Aged beautifully",
    gem: true,
    libretroName: "Vectorman (USA)",
  },
  {
    id: "gen-15",
    name: "Beyond Oasis",
    platform: "Genesis",
    genres: ["Action", "Adventure"],
    notes: "Sega's answer to Zelda",
    gem: false,
    libretroName: "Beyond Oasis (USA)",
  },
  {
    id: "gen-16",
    name: "Ranger X",
    platform: "Genesis",
    genres: ["Action"],
    notes: "Innovative mech shooter",
    gem: true,
    libretroName: "Ranger X (USA)",
  },
  {
    id: "gen-17",
    name: "Strider",
    platform: "Genesis",
    genres: ["Action"],
    notes: "Fluid acrobatic action",
    gem: false,
    libretroName: "Strider (USA)",
  },
  {
    id: "gen-18",
    name: "M.U.S.H.A.",
    platform: "Genesis",
    genres: ["Shmup"],
    notes: "Aleste series finest",
    gem: true,
    libretroName: "MUSHA (USA)",
  },
  {
    id: "gen-19",
    name: "Street Fighter II': SCE",
    platform: "Genesis",
    genres: ["Fighting"],
    notes: "Definitive 16-bit SF2",
    gem: false,
    libretroName: "Street Fighter II' - Special Champion Edition (USA)",
  },
  {
    id: "gen-20",
    name: "Golden Axe",
    platform: "Genesis",
    genres: ["Beat-Em-Up"],
    notes: "Classic fantasy brawler",
    gem: false,
    libretroName: "Golden Axe (World) (Rev A)",
  },
  {
    id: "gen-21",
    name: "NHL '94",
    platform: "Genesis",
    genres: ["Sports"],
    notes: "Greatest sports game ever",
    gem: false,
    libretroName: "NHL '94 (USA)",
  },
  {
    id: "gen-22",
    name: "Road Rash II",
    platform: "Genesis",
    genres: ["Racing"],
    notes: "Combat motorcycle racing",
    gem: false,
    libretroName: "Road Rash II (USA)",
  },
  {
    id: "gen-23",
    name: "ToeJam & Earl",
    platform: "Genesis",
    genres: ["Roguelike"],
    notes: "Funky alien adventure",
    gem: false,
    libretroName: "ToeJam & Earl (USA, Europe)",
  },
  {
    id: "gen-24",
    name: "Dr. Robotnik's Mean Bean Machine",
    platform: "Genesis",
    genres: ["Puzzle"],
    notes: "Best falling-block",
    gem: false,
    libretroName: "Dr. Robotnik's Mean Bean Machine (USA)",
  },
  {
    id: "gen-25",
    name: "Columns",
    platform: "Genesis",
    genres: ["Puzzle"],
    notes: "Addictive match-3",
    gem: false,
    libretroName: "Columns (World)",
  },
  {
    id: "gen-26",
    name: "Sonic the Hedgehog 3",
    platform: "Genesis",
    genres: ["Platformer"],
    notes: "Standalone, save system",
    gem: false,
    libretroName: "Sonic The Hedgehog 3 (USA)",
  },
  {
    id: "gen-27",
    name: "Ecco the Dolphin",
    platform: "Genesis",
    genres: ["Adventure"],
    notes: "Haunting, meditative",
    gem: false,
    libretroName: "Ecco the Dolphin (USA, Europe, Korea) (En)",
  },
  {
    id: "gen-28",
    name: "General Chaos",
    platform: "Genesis",
    genres: ["Strategy"],
    notes: "5v5 cartoon warfare",
    gem: true,
    libretroName: "General Chaos (USA)",
  },
  {
    id: "gen-29",
    name: "Micro Machines 2",
    platform: "Genesis",
    genres: ["Racing"],
    notes: "8-player mode",
    gem: true,
    libretroName: "Micro Machines 2 - Turbo Tournament (Europe)",
  },
  {
    id: "gen-30",
    name: "The Ooze",
    platform: "Genesis",
    genres: ["Action"],
    notes: "Play as toxic sludge",
    gem: true,
    libretroName: "Ooze, The (USA)",
  },
  {
    id: "gen-31",
    name: "Wiz 'n' Liz",
    platform: "Genesis",
    genres: ["Action"],
    notes: "Frantic spell-mixing",
    gem: true,
    libretroName: "Wiz 'n' Liz (USA)",
  },
  {
    id: "gen-32",
    name: "Dragon's Fury",
    platform: "Genesis",
    genres: ["Pinball"],
    notes: "Best Genesis pinball, dark fantasy theme with bonus boss battles",
    gem: false,
    libretroName: "Dragon's Fury (USA)",
  },
  {
    id: "gen-33",
    name: "Psycho Pinball",
    platform: "Genesis",
    genres: ["Pinball"],
    notes: "Four interconnected tables, fantastic art and music",
    gem: true,
    libretroName: "Psycho Pinball (Europe)",
  },

  // NES (20 games)
  {
    id: "nes-1",
    name: "Super Mario Bros. 3",
    platform: "NES",
    genres: ["Platformer"],
    notes: "Apex of 8-bit design",
    gem: false,
    libretroName: "Super Mario Bros. 3 (USA)",
  },
  {
    id: "nes-2",
    name: "The Legend of Zelda",
    platform: "NES",
    genres: ["Action", "Adventure"],
    notes: "Groundbreaking exploration",
    gem: false,
    libretroName: "Legend of Zelda, The (USA)",
  },
  {
    id: "nes-3",
    name: "Mega Man 2",
    platform: "NES",
    genres: ["Platformer", "Action"],
    notes: "Perfect difficulty, iconic OST",
    gem: false,
    libretroName: "Mega Man 2 (USA)",
  },
  {
    id: "nes-4",
    name: "Metroid",
    platform: "NES",
    genres: ["Action", "Adventure"],
    notes: "Atmospheric exploration",
    gem: false,
    libretroName: "Metroid (USA)",
  },
  {
    id: "nes-5",
    name: "Super Mario Bros.",
    platform: "NES",
    genres: ["Platformer"],
    notes: "Saved the industry",
    gem: false,
    libretroName: "Super Mario Bros. (World)",
  },
  {
    id: "nes-6",
    name: "Castlevania",
    platform: "NES",
    genres: ["Action"],
    notes: "Methodical vampire hunting",
    gem: false,
    libretroName: "Castlevania (USA)",
  },
  {
    id: "nes-7",
    name: "Contra",
    platform: "NES",
    genres: ["Action"],
    notes: "Essential 2-player co-op",
    gem: false,
    libretroName: "Contra (USA)",
  },
  {
    id: "nes-8",
    name: "Ninja Gaiden",
    platform: "NES",
    genres: ["Action"],
    notes: "Cinematic, tight controls",
    gem: false,
    libretroName: "Ninja Gaiden (USA)",
  },
  {
    id: "nes-9",
    name: "Kirby's Adventure",
    platform: "NES",
    genres: ["Platformer"],
    notes: "Gorgeous late-era NES",
    gem: false,
    libretroName: "Kirby's Adventure (USA)",
  },
  {
    id: "nes-10",
    name: "DuckTales",
    platform: "NES",
    genres: ["Platformer"],
    notes: "Capcom masterpiece",
    gem: true,
    libretroName: "DuckTales (USA)",
  },
  {
    id: "nes-11",
    name: "Dragon Quest III",
    platform: "NES",
    genres: ["RPG"],
    notes: "Definitive 8-bit JRPG",
    gem: false,
    libretroName: "Dragon Warrior III (USA)",
  },
  {
    id: "nes-12",
    name: "Final Fantasy",
    platform: "NES",
    genres: ["RPG"],
    notes: "Where it began",
    gem: false,
    libretroName: "Final Fantasy (USA)",
  },
  {
    id: "nes-13",
    name: "Punch-Out!!",
    platform: "NES",
    genres: ["Sports"],
    notes: "Pattern memorization",
    gem: false,
    libretroName: "Mike Tyson's Punch-Out!! (USA)",
  },
  {
    id: "nes-14",
    name: "Tetris",
    platform: "NES",
    genres: ["Puzzle"],
    notes: "Definitive competitive version",
    gem: false,
    libretroName: "Tetris (USA)",
  },
  {
    id: "nes-15",
    name: "Bionic Commando",
    platform: "NES",
    genres: ["Action"],
    notes: "Unique grappling traversal",
    gem: false,
    libretroName: "Bionic Commando (USA)",
  },
  {
    id: "nes-16",
    name: "River City Ransom",
    platform: "NES",
    genres: ["Beat-Em-Up", "RPG"],
    notes: "Open-world brawler",
    gem: true,
    libretroName: "River City Ransom (USA)",
  },
  {
    id: "nes-17",
    name: "Crystalis",
    platform: "NES",
    genres: ["Action", "RPG"],
    notes: "NES Zelda killer",
    gem: true,
    libretroName: "Crystalis (USA)",
  },
  {
    id: "nes-18",
    name: "Bubble Bobble",
    platform: "NES",
    genres: ["Puzzle", "Platformer"],
    notes: "Charming co-op",
    gem: true,
    libretroName: "Bubble Bobble (USA)",
  },
  {
    id: "nes-19",
    name: "Tecmo Super Bowl",
    platform: "NES",
    genres: ["Sports"],
    notes: "Still modded today",
    gem: true,
    libretroName: "Tecmo Super Bowl (USA)",
  },
  {
    id: "nes-20",
    name: "Blaster Master",
    platform: "NES",
    genres: ["Action", "Adventure"],
    notes: "Vehicle/on-foot hybrid",
    gem: true,
    libretroName: "Blaster Master (USA)",
  },

  // N64 (15 games)
  {
    id: "n64-1",
    name: "Zelda: Ocarina of Time",
    platform: "N64",
    genres: ["Action", "Adventure"],
    notes: "Revolutionary, defined 3D",
    gem: false,
    libretroName: "Legend of Zelda, The - Ocarina of Time (USA)",
  },
  {
    id: "n64-2",
    name: "Super Mario 64",
    platform: "N64",
    genres: ["Platformer"],
    notes: "Template for 3D platformers",
    gem: false,
    libretroName: "Super Mario 64 (USA)",
  },
  {
    id: "n64-3",
    name: "Banjo-Kazooie",
    platform: "N64",
    genres: ["Platformer"],
    notes: "Rivals Mario 64",
    gem: false,
    libretroName: "Banjo-Kazooie (USA)",
  },
  {
    id: "n64-4",
    name: "Paper Mario",
    platform: "N64",
    genres: ["RPG"],
    notes: "2D aesthetic aged well",
    gem: false,
    libretroName: "Paper Mario (USA)",
  },
  {
    id: "n64-5",
    name: "Mario Kart 64",
    platform: "N64",
    genres: ["Racing"],
    notes: "4-player legendary",
    gem: false,
    libretroName: "Mario Kart 64 (USA)",
  },
  {
    id: "n64-6",
    name: "Star Fox 64",
    platform: "N64",
    genres: ["Shooter"],
    notes: "Branching paths, replay value",
    gem: false,
    libretroName: "Star Fox 64 (USA)",
  },
  {
    id: "n64-7",
    name: "F-Zero X",
    platform: "N64",
    genres: ["Racing"],
    notes: "60fps, blazing fast",
    gem: false,
    libretroName: "F-Zero X (USA)",
  },
  {
    id: "n64-8",
    name: "Perfect Dark",
    platform: "N64",
    genres: ["Shooter"],
    notes: "Better than GoldenEye",
    gem: false,
    libretroName: "Perfect Dark (USA)",
  },
  {
    id: "n64-9",
    name: "Super Smash Bros.",
    platform: "N64",
    genres: ["Fighting"],
    notes: "Foundation of franchise",
    gem: false,
    libretroName: "Super Smash Bros. (USA)",
  },
  {
    id: "n64-10",
    name: "Wave Race 64",
    platform: "N64",
    genres: ["Racing"],
    notes: "Dynamic water physics",
    gem: false,
    libretroName: "Wave Race 64 (USA) (Rev 1)",
  },
  {
    id: "n64-11",
    name: "Pokémon Snap",
    platform: "N64",
    genres: ["Simulation"],
    notes: "Unique concept, holds up",
    gem: false,
    libretroName: "Pokemon Snap (USA)",
  },
  {
    id: "n64-12",
    name: "ISS '98",
    platform: "N64",
    genres: ["Sports"],
    notes: "Best football on N64",
    gem: false,
    libretroName: "International Superstar Soccer '98 (USA)",
  },
  {
    id: "n64-13",
    name: "Mischief Makers",
    platform: "N64",
    genres: ["Action", "Platformer"],
    notes: "Treasure side-scroller",
    gem: true,
    libretroName: "Mischief Makers (USA)",
  },
  {
    id: "n64-14",
    name: "Blast Corps",
    platform: "N64",
    genres: ["Action"],
    notes: "Demolition chaos",
    gem: true,
    libretroName: "Blast Corps (USA)",
  },
  {
    id: "n64-15",
    name: "Pilotwings 64",
    platform: "N64",
    genres: ["Simulation"],
    notes: "Relaxing, tight controls",
    gem: false,
    libretroName: "Pilotwings 64 (USA)",
  },

  // PS1 (31 games)
  {
    id: "ps1-1",
    name: "Final Fantasy VII",
    platform: "PS1",
    genres: ["RPG"],
    notes: "Crown jewel of PS1 RPGs",
    gem: false,
    libretroName: "Final Fantasy VII (USA) (Disc 1)",
  },
  {
    id: "ps1-2",
    name: "Metal Gear Solid",
    platform: "PS1",
    genres: ["Stealth", "Action"],
    notes: "Defined stealth gaming",
    gem: false,
    libretroName: "Metal Gear Solid (USA) (Disc 1) (Rev 1)",
  },
  {
    id: "ps1-3",
    name: "Castlevania: Symphony of the Night",
    platform: "PS1",
    genres: ["Action", "Adventure"],
    notes: "2D masterpiece",
    gem: false,
    libretroName: "Castlevania - Symphony of the Night (USA)",
  },
  {
    id: "ps1-4",
    name: "Chrono Cross",
    platform: "PS1",
    genres: ["RPG"],
    notes: "Stunning visuals, legendary OST",
    gem: false,
    libretroName: "Chrono Cross (USA) (Disc 1)",
  },
  {
    id: "ps1-5",
    name: "Resident Evil 2",
    platform: "PS1",
    genres: ["Horror"],
    notes: "Bigger, scarier, iconic",
    gem: false,
    libretroName: "Resident Evil 2 (USA) (Disc 1)",
  },
  {
    id: "ps1-6",
    name: "Silent Hill",
    platform: "PS1",
    genres: ["Horror"],
    notes: "Psychological horror",
    gem: false,
    libretroName: "Silent Hill (USA)",
  },
  {
    id: "ps1-7",
    name: "Suikoden II",
    platform: "PS1",
    genres: ["RPG"],
    notes: "Cult classic, 108 characters",
    gem: false,
    libretroName: "Suikoden II (USA)",
  },
  {
    id: "ps1-8",
    name: "Xenogears",
    platform: "PS1",
    genres: ["RPG"],
    notes: "Dense philosophical narrative",
    gem: false,
    libretroName: "Xenogears (USA) (Disc 1)",
  },
  {
    id: "ps1-9",
    name: "Vagrant Story",
    platform: "PS1",
    genres: ["Action", "RPG"],
    notes: "Square's technical masterpiece",
    gem: false,
    libretroName: "Vagrant Story (USA)",
  },
  {
    id: "ps1-10",
    name: "Final Fantasy Tactics",
    platform: "PS1",
    genres: ["Strategy", "RPG"],
    notes: "Deep tactical gameplay",
    gem: false,
    libretroName: "Final Fantasy Tactics (USA)",
  },
  {
    id: "ps1-11",
    name: "Crash Bandicoot: Warped",
    platform: "PS1",
    genres: ["Platformer"],
    notes: "Peak Crash with variety",
    gem: false,
    libretroName: "Crash Bandicoot 3 - Warped (USA)",
  },
  {
    id: "ps1-12",
    name: "Spyro the Dragon",
    platform: "PS1",
    genres: ["Platformer"],
    notes: "PS1 could do 3D platforming",
    gem: false,
    libretroName: "Spyro the Dragon (USA)",
  },
  {
    id: "ps1-13",
    name: "Gran Turismo 2",
    platform: "PS1",
    genres: ["Racing"],
    notes: "Definitive PS1 racer",
    gem: false,
    libretroName: "Gran Turismo 2 (USA) (Arcade Mode)",
  },
  {
    id: "ps1-14",
    name: "WipEout 2097",
    platform: "PS1",
    genres: ["Racing"],
    notes: "Iconic soundtrack, futuristic",
    gem: false,
    libretroName: "Wipeout XL (USA)",
  },
  {
    id: "ps1-15",
    name: "Tekken 3",
    platform: "PS1",
    genres: ["Fighting"],
    notes: "Peak 3D fighting on PS1",
    gem: false,
    libretroName: "Tekken 3 (USA)",
  },
  {
    id: "ps1-16",
    name: "Tony Hawk's Pro Skater 2",
    platform: "PS1",
    genres: ["Sports"],
    notes: "Manual mechanic, park editor",
    gem: false,
    libretroName: "Tony Hawk's Pro Skater 2 (USA)",
  },
  {
    id: "ps1-17",
    name: "Tomb Raider",
    platform: "PS1",
    genres: ["Action", "Adventure"],
    notes: "Exploration/puzzle combo",
    gem: false,
    libretroName: "Tomb Raider (USA)",
  },
  {
    id: "ps1-18",
    name: "Tenchu: Stealth Assassins",
    platform: "PS1",
    genres: ["Stealth", "Action"],
    notes: "First authentic ninja game",
    gem: false,
    libretroName: "Tenchu - Stealth Assassins (USA)",
  },
  {
    id: "ps1-19",
    name: "Oddworld: Abe's Oddysee",
    platform: "PS1",
    genres: ["Platformer", "Puzzle"],
    notes: "Dark humor, unique mechanics",
    gem: false,
    libretroName: "Oddworld - Abe's Oddysee (USA)",
  },
  {
    id: "ps1-20",
    name: "PaRappa the Rapper",
    platform: "PS1",
    genres: ["Rhythm"],
    notes: "Birth of rhythm games",
    gem: false,
    libretroName: "PaRappa the Rapper (USA)",
  },
  {
    id: "ps1-21",
    name: "Ape Escape",
    platform: "PS1",
    genres: ["Platformer"],
    notes: "First DualShock required",
    gem: false,
    libretroName: "Ape Escape (USA)",
  },
  {
    id: "ps1-22",
    name: "Twisted Metal 2",
    platform: "PS1",
    genres: ["Action"],
    notes: "Global arenas",
    gem: false,
    libretroName: "Twisted Metal 2 (USA)",
  },
  {
    id: "ps1-23",
    name: "Ridge Racer Type 4",
    platform: "PS1",
    genres: ["Racing"],
    notes: "321 unlockable vehicles",
    gem: false,
    libretroName: "R4 - Ridge Racer Type 4 (USA)",
  },
  {
    id: "ps1-24",
    name: "Street Fighter Alpha 3",
    platform: "PS1",
    genres: ["Fighting"],
    notes: "Arcade perfect + World Tour",
    gem: false,
    libretroName: "Street Fighter Alpha 3 (USA)",
  },
  {
    id: "ps1-25",
    name: "Driver",
    platform: "PS1",
    genres: ["Action", "Racing"],
    notes: "70s car chases",
    gem: false,
    libretroName: "Driver (USA)",
  },
  {
    id: "ps1-26",
    name: "Parasite Eve",
    platform: "PS1",
    genres: ["Action", "RPG", "Horror"],
    notes: "Survival RPG blend",
    gem: true,
    libretroName: "Parasite Eve (USA) (Disc 1)",
  },
  {
    id: "ps1-27",
    name: "Dino Crisis",
    platform: "PS1",
    genres: ["Horror"],
    notes: "Panic horror",
    gem: true,
    libretroName: "Dino Crisis (USA)",
  },
  {
    id: "ps1-28",
    name: "Tomba!",
    platform: "PS1",
    genres: ["Platformer", "Adventure"],
    notes: "2.5D with quests",
    gem: true,
    libretroName: "Tomba! (USA)",
  },
  {
    id: "ps1-29",
    name: "Einhänder",
    platform: "PS1",
    genres: ["Shmup"],
    notes: "Square's shooter",
    gem: true,
    libretroName: "Einhander (USA)",
  },
  {
    id: "ps1-30",
    name: "Alundra",
    platform: "PS1",
    genres: ["Action", "RPG"],
    notes: "Best 2D Zelda clone",
    gem: true,
    libretroName: "Alundra (USA)",
  },
  {
    id: "ps1-31",
    name: "Brave Fencer Musashi",
    platform: "PS1",
    genres: ["Action", "RPG"],
    notes: "Underrated Squaresoft action-RPG gem",
    gem: true,
    libretroName: "Brave Fencer Musashi (USA)",
  },

  // GB/GBC (16 games)
  {
    id: "gb-1",
    name: "Pokémon Crystal",
    platform: "GB/GBC",
    genres: ["RPG"],
    notes: "Definitive Gen II",
    gem: false,
    libretroName: "Pokemon - Crystal Version (USA, Europe)",
  },
  {
    id: "gb-2",
    name: "Link's Awakening DX",
    platform: "GB/GBC",
    genres: ["Action", "Adventure"],
    notes: "Arguably best 2D Zelda",
    gem: false,
    libretroName: "Legend of Zelda, The - Link's Awakening DX (USA, Europe)",
  },
  {
    id: "gb-3",
    name: "Oracle of Seasons",
    platform: "GB/GBC",
    genres: ["Action", "Adventure"],
    notes: "Combat-focused Zelda",
    gem: false,
    libretroName: "Legend of Zelda, The - Oracle of Seasons (USA)",
  },
  {
    id: "gb-4",
    name: "Oracle of Ages",
    platform: "GB/GBC",
    genres: ["Action", "Adventure"],
    notes: "Puzzle-focused companion",
    gem: false,
    libretroName: "Legend of Zelda, The - Oracle of Ages (USA)",
  },
  {
    id: "gb-5",
    name: "Metal Gear Solid",
    platform: "GB/GBC",
    genres: ["Stealth", "Action"],
    notes: "Faithful portable MGS",
    gem: true,
    libretroName: "Metal Gear Solid (USA)",
  },
  {
    id: "gb-6",
    name: "Super Mario Land 2",
    platform: "GB/GBC",
    genres: ["Platformer"],
    notes: "Introduced Wario",
    gem: false,
    libretroName: "Super Mario Land 2 - 6 Golden Coins (USA, Europe)",
  },
  {
    id: "gb-7",
    name: "Wario Land 3",
    platform: "GB/GBC",
    genres: ["Platformer", "Puzzle"],
    notes: "Immortal Wario, puzzles",
    gem: false,
    libretroName: "Wario Land 3 (USA)",
  },
  {
    id: "gb-8",
    name: "Donkey Kong",
    platform: "GB/GBC",
    genres: ["Puzzle", "Platformer"],
    notes: "100+ levels",
    gem: true,
    libretroName: "Donkey Kong (World) (Rev 1) (SGB Enhanced)",
  },
  {
    id: "gb-9",
    name: "Shantae",
    platform: "GB/GBC",
    genres: ["Platformer", "Adventure"],
    notes: "Late-release Metroidvania",
    gem: true,
    libretroName: "Shantae (USA)",
  },
  {
    id: "gb-10",
    name: "Kirby's Dream Land 2",
    platform: "GB/GBC",
    genres: ["Platformer"],
    notes: "Copy abilities, animals",
    gem: false,
    libretroName: "Kirby's Dream Land 2 (USA, Europe)",
  },
  {
    id: "gb-11",
    name: "Tetris DX",
    platform: "GB/GBC",
    genres: ["Puzzle"],
    notes: "Definitive GB Tetris",
    gem: false,
    libretroName: "Tetris DX (USA, Europe)",
  },
  {
    id: "gb-12",
    name: "Pokémon Puzzle Challenge",
    platform: "GB/GBC",
    genres: ["Puzzle"],
    notes: "Incredibly addictive",
    gem: true,
    libretroName: "Pokemon Puzzle Challenge (USA)",
  },
  {
    id: "gb-13",
    name: "Mario Tennis",
    platform: "GB/GBC",
    genres: ["Sports", "RPG"],
    notes: "Deep career mode",
    gem: false,
    libretroName: "Mario Tennis (USA)",
  },
  {
    id: "gb-14",
    name: "Mario Golf",
    platform: "GB/GBC",
    genres: ["Sports", "RPG"],
    notes: "Full-featured with progression",
    gem: false,
    libretroName: "Mario Golf (USA)",
  },
  {
    id: "gb-15",
    name: "Metroid II: Return of Samus",
    platform: "GB/GBC",
    genres: ["Action", "Adventure"],
    notes: "Atmospheric expansion",
    gem: false,
    libretroName: "Metroid II - Return of Samus (World)",
  },
  {
    id: "gb-16",
    name: "Cannon Fodder",
    platform: "GB/GBC",
    genres: ["Action", "Strategy"],
    notes: "Dark humor war game, surprisingly great handheld port",
    gem: true,
    libretroName: "Cannon Fodder (Europe) (En,Fr,De)",
  },

  // Saturn (15 games)
  {
    id: "sat-1",
    name: "Panzer Dragoon Saga",
    platform: "Saturn",
    genres: ["RPG"],
    notes: "Saturn's crown jewel",
    gem: false,
    libretroName: "Panzer Dragoon Saga (USA) (Disc 1)",
  },
  {
    id: "sat-2",
    name: "Radiant Silvergun",
    platform: "Saturn",
    genres: ["Shmup"],
    notes: "Legendary, innovative",
    gem: false,
    libretroName: "Radiant Silvergun (Japan)",
  },
  {
    id: "sat-3",
    name: "Guardian Heroes",
    platform: "Saturn",
    genres: ["Beat-Em-Up", "RPG"],
    notes: "Genre-bending brawler",
    gem: false,
    libretroName: "Guardian Heroes (USA)",
  },
  {
    id: "sat-4",
    name: "NiGHTS Into Dreams",
    platform: "Saturn",
    genres: ["Action"],
    notes: "Dreamlike score-attack",
    gem: false,
    libretroName: "Nights Into Dreams... (USA)",
  },
  {
    id: "sat-5",
    name: "Shining Force III",
    platform: "Saturn",
    genres: ["Strategy", "RPG"],
    notes: "Deep tactics",
    gem: false,
    libretroName: "Shining Force III (USA)",
  },
  {
    id: "sat-6",
    name: "Dragon Force",
    platform: "Saturn",
    genres: ["Strategy", "RPG"],
    notes: "Massive army battles",
    gem: true,
    libretroName: "Dragon Force (USA)",
  },
  {
    id: "sat-7",
    name: "Shining the Holy Ark",
    platform: "Saturn",
    genres: ["RPG"],
    notes: "First-person dungeon crawler",
    gem: false,
    libretroName: "Shining the Holy Ark (USA)",
  },
  {
    id: "sat-8",
    name: "X-Men vs. Street Fighter",
    platform: "Saturn",
    genres: ["Fighting"],
    notes: "Import essential",
    gem: false,
    libretroName: "X-Men vs. Street Fighter (Japan)",
  },
  {
    id: "sat-9",
    name: "Virtua Fighter 2",
    platform: "Saturn",
    genres: ["Fighting"],
    notes: "Groundbreaking 3D",
    gem: false,
    libretroName: "Virtua Fighter 2 (USA)",
  },
  {
    id: "sat-10",
    name: "Fighters Megamix",
    platform: "Saturn",
    genres: ["Fighting"],
    notes: "Wild crossover",
    gem: false,
    libretroName: "Fighters Megamix (USA)",
  },
  {
    id: "sat-11",
    name: "Panzer Dragoon II Zwei",
    platform: "Saturn",
    genres: ["Shooter"],
    notes: "Dragon evolution",
    gem: false,
    libretroName: "Panzer Dragoon II Zwei (USA)",
  },
  {
    id: "sat-12",
    name: "Sega Rally Championship",
    platform: "Saturn",
    genres: ["Racing"],
    notes: "Handling still fantastic",
    gem: false,
    libretroName: "Sega Rally Championship (USA)",
  },
  {
    id: "sat-13",
    name: "Saturn Bomberman",
    platform: "Saturn",
    genres: ["Party"],
    notes: "10-player chaos",
    gem: false,
    libretroName: "Saturn Bomberman (USA)",
  },
  {
    id: "sat-14",
    name: "Darius Gaiden",
    platform: "Saturn",
    genres: ["Shmup"],
    notes: "Stunning 2D visuals",
    gem: true,
    libretroName: "Darius Gaiden (Japan)",
  },
  {
    id: "sat-15",
    name: "Burning Rangers",
    platform: "Saturn",
    genres: ["Action"],
    notes: "Sonic Team firefighting",
    gem: true,
    libretroName: "Burning Rangers (USA)",
  },

  // Master System (14 games)
  {
    id: "sms-1",
    name: "Phantasy Star",
    platform: "Master System",
    genres: ["RPG"],
    notes: "Groundbreaking 8-bit RPG with 3D dungeons and female protagonist",
    gem: false,
    libretroName: "Phantasy Star (USA, Europe) (v1.3)",
  },
  {
    id: "sms-2",
    name: "Wonder Boy III: The Dragon's Trap",
    platform: "Master System",
    genres: ["Action", "Adventure", "Platformer"],
    notes: "Metroidvania pioneer, EGM's 1989 SMS Game of the Year",
    gem: false,
    libretroName: "Wonder Boy III - The Dragon's Trap (USA, Europe)",
  },
  {
    id: "sms-3",
    name: "Golden Axe Warrior",
    platform: "Master System",
    genres: ["Action", "Adventure"],
    notes: "Zelda-style adventure that improves on the formula",
    gem: true,
    libretroName: "Golden Axe Warrior (USA, Europe)",
  },
  {
    id: "sms-4",
    name: "Alex Kidd in Miracle World",
    platform: "Master System",
    genres: ["Platformer"],
    notes: "Sega's pre-Sonic mascot, built into SMS II consoles",
    gem: false,
    libretroName: "Alex Kidd in Miracle World (USA, Europe)",
  },
  {
    id: "sms-5",
    name: "Sonic the Hedgehog",
    platform: "Master System",
    genres: ["Platformer"],
    notes: "Unique 8-bit version with original levels, not a port",
    gem: false,
    libretroName: "Sonic the Hedgehog (USA, Europe)",
  },
  {
    id: "sms-6",
    name: "Castle of Illusion Starring Mickey Mouse",
    platform: "Master System",
    genres: ["Platformer"],
    notes: "Rated best SMS game of all time by Sega Power",
    gem: false,
    libretroName: "Castle of Illusion Starring Mickey Mouse (USA, Europe)",
  },
  {
    id: "sms-7",
    name: "Land of Illusion Starring Mickey Mouse",
    platform: "Master System",
    genres: ["Platformer", "Adventure"],
    notes: "Built from ground up for SMS, Metroidvania elements",
    gem: true,
    libretroName: "Land of Illusion Starring Mickey Mouse (USA, Europe)",
  },
  {
    id: "sms-8",
    name: "Psycho Fox",
    platform: "Master System",
    genres: ["Platformer"],
    notes: "Mario meets Sonic hybrid, highly acclaimed",
    gem: true,
    libretroName: "Psycho Fox (USA, Europe)",
  },
  {
    id: "sms-9",
    name: "Shinobi",
    platform: "Master System",
    genres: ["Action", "Platformer"],
    notes: "Origin of Sega's legendary ninja franchise",
    gem: false,
    libretroName: "Shinobi (USA, Europe)",
  },
  {
    id: "sms-10",
    name: "Alex Kidd in Shinobi World",
    platform: "Master System",
    genres: ["Action", "Platformer"],
    notes: "Charming parody mashup that works surprisingly well",
    gem: true,
    libretroName: "Alex Kidd in Shinobi World (USA, Europe)",
  },
  {
    id: "sms-11",
    name: "OutRun",
    platform: "Master System",
    genres: ["Racing"],
    notes: "Impressive arcade port, iconic soundtrack",
    gem: false,
    libretroName: "Out Run (USA, Europe)",
  },
  {
    id: "sms-12",
    name: "Bubble Bobble",
    platform: "Master System",
    genres: ["Puzzle", "Platformer"],
    notes: "200 levels, enhanced port with co-op",
    gem: false,
    libretroName: "Bubble Bobble (Europe)",
  },
  {
    id: "sms-13",
    name: "Zillion",
    platform: "Master System",
    genres: ["Action", "Adventure"],
    notes: "Metroid-influenced exploration, based on anime",
    gem: true,
    libretroName: "Zillion (USA, Europe)",
  },
  {
    id: "sms-14",
    name: "Wonder Boy in Monster Land",
    platform: "Master System",
    genres: ["Action", "Adventure"],
    notes: "Action-RPG hybrid that defined the series",
    gem: false,
    libretroName: "Wonder Boy in Monster Land (USA, Europe)",
  },
];
